version: '3.8'
services:
  dev-db:
    image: postgres:13
    # build: ./db
    env_file:
      - .env
    ports:
      - 5432:5432
    # volumes:
      # - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./db/data:/var/lib/postgresql/data
    restart: always
    container_name: nest-db

  # api:
  #   build: .
  #   env_file:
  #     - .env
  #   depends_on:
  #     - dev-db
  #   ports:
  #     - 8080:3001
  #   restart: always
  #   container_name: nest-api
